INSERT INTO `instalaciones` VALUES
(1, 'Instalaciones internas', 'edificio-11.jpg', 'a', 4),
(2, 'Edificio 2', 'edificio-2.jpg', 'a', 4),
(3, 'edificio 3', 'edificio-3.jpg', 'a', 4),
(4, 'Consultorios', 'consultorios-1.jpg', 'a', 6),
(5, 'Consultorios 2', 'consultorios-2.jpg', 'a', 6),
(6, 'Equipamiento', 'equipamiento-tecnico-1.jpg', 'a', 7),
(7, 'Equipamiento 2', 'equipamiento-tecnico-2.jpg', 'a', 7),
(8, 'Equipamiento 3', 'equipamiento-tecnico-3.jpg', 'a', 7),
(11, 'Equipamiento 4', 'equipamiento-tecnico-4.jpg', 'a', 7),
(12, 'Equipamiento 5', 'equipamiento-tecnico-5.jpg', 'a', 7),
(13, 'Equipamiento 6', 'equipamiento-tecnico-6.jpg', 'a', 7),
(14, 'Equipamiento 7', 'equipamiento-tecnico-7.jpg', 'a', 7),
(16, 'Equipamiento 8', 'equipamiento-tecnico-9.jpg', 'a', 7),
(17, 'Equipamiento 10', 'equipamiento-tecnico-10.jpg', 'a', 7),
(18, 'Equipamiento 11', 'equipamiento-tecnico-11_1.jpg', 'a', 7),
(19, 'Equipamiento 12', 'equipamiento-tecnico-11_2.jpg', 'a', 7),
(20, 'Habitaciones', 'habitaciones-0.jpg', 'a', 3),
(21, 'Habitaciones 2', 'habitaciones-1.jpg', 'a', 3),
(22, 'Habitaciones 3', 'habitaciones-2.jpg', 'a', 3),
(23, 'Habitaciones 4', 'habitaciones-3.jpg', 'a', 3),
(24, 'Habitaciones 5', 'habitaciones-4.jpg', 'a', 3),
(25, 'Habitaciones 6', 'habitaciones-5.jpg', 'a', 3),
(26, 'Habitaciones 7', 'habitaciones-6.jpg', 'a', 3),
(27, 'Laboratorio', 'laboratorio-1.jpg', 'a', 8),
(28, 'Laboratorio 2', 'laboratorio-2.jpg', 'a', 8),
(29, 'Laboratorio 3', 'laboratorio-3.jpg', 'a', 8),
(30, 'Pediatría', 'pediatria-1.jpg', 'a', 9),
(31, 'Pediatría 2', 'pediatria-2.jpg', 'a', 9),
(32, 'Pediatría 3', 'pediatria-3.jpg', 'a', 9),
(33, 'Sala de espera', 'sala-de-espera-0_1.jpg', 'a', 1),
(34, 'Sala de espera 2', 'sala-de-espera-0_2.jpg', 'a', 1),
(35, 'Sala de espera 3', 'sala-de-espera-0.jpg', 'a', 1),
(36, 'Sala de espera 4', 'sala-de-espera-1.jpg', 'a', 1),
(37, 'Sala de espera 5', 'sala-de-espera-2.jpg', 'a', 1),
(38, 'Sala de espera 6', 'sala-de-espera-3.jpg', 'a', 1),
(39, 'Sala de espera 7', 'sala-de-espera-4.jpg', 'a', 1),
(40, 'Sala de espera 8', 'sala-de-espera-5.jpg', 'a', 1);
