INSERT INTO `instalaciones` VALUES (1, 'Instalaciones internas', 'edificio-11.jpg', 'a', 4);
INSERT INTO `instalaciones` VALUES (2, 'Edificio 2', 'edificio-2.jpg', 'a', 4);
INSERT INTO `instalaciones` VALUES (3, 'edificio 3', 'edificio-3.jpg', 'a', 4);
INSERT INTO `instalaciones` VALUES (4, 'Consultorios', 'consultorios-1.jpg', 'a', 6);
INSERT INTO `instalaciones` VALUES (5, 'Consultorios 2', 'consultorios-2.jpg', 'a', 6);
INSERT INTO `instalaciones` VALUES (6, 'Equipamiento', 'equipamiento-tecnico-1.jpg', 'a', 7);
INSERT INTO `instalaciones` VALUES (7, 'Equipamiento 2', 'equipamiento-tecnico-2.jpg', 'a', 7);
INSERT INTO `instalaciones` VALUES (8, 'Equipamiento 3', 'equipamiento-tecnico-3.jpg', 'a', 7);
INSERT INTO `instalaciones` VALUES (11, 'Equipamiento 4', 'equipamiento-tecnico-4.jpg', 'a', 7);
INSERT INTO `instalaciones` VALUES (12, 'Equipamiento 5', 'equipamiento-tecnico-5.jpg', 'a', 7);
INSERT INTO `instalaciones` VALUES (13, 'Equipamiento 6', 'equipamiento-tecnico-6.jpg', 'a', 7);
INSERT INTO `instalaciones` VALUES (14, 'Equipamiento 7', 'equipamiento-tecnico-7.jpg', 'a', 7);
INSERT INTO `instalaciones` VALUES (16, 'Equipamiento 8', 'equipamiento-tecnico-9.jpg', 'a', 7);
INSERT INTO `instalaciones` VALUES (17, 'Equipamiento 10', 'equipamiento-tecnico-10.jpg', 'a', 7);
INSERT INTO `instalaciones` VALUES (18, 'Equipamiento 11', 'equipamiento-tecnico-11_1.jpg', 'a', 7);
INSERT INTO `instalaciones` VALUES (19, 'Equipamiento 12', 'equipamiento-tecnico-11_2.jpg', 'a', 7);
INSERT INTO `instalaciones` VALUES (20, 'Habitaciones', 'habitaciones-0.jpg', 'a', 3);
INSERT INTO `instalaciones` VALUES (21, 'Habitaciones 2', 'habitaciones-1.jpg', 'a', 3);
INSERT INTO `instalaciones` VALUES (22, 'Habitaciones 3', 'habitaciones-2.jpg', 'a', 3);
INSERT INTO `instalaciones` VALUES (23, 'Habitaciones 4', 'habitaciones-3.jpg', 'a', 3);
INSERT INTO `instalaciones` VALUES (24, 'Habitaciones 5', 'habitaciones-4.jpg', 'a', 3);
INSERT INTO `instalaciones` VALUES (25, 'Habitaciones 6', 'habitaciones-5.jpg', 'a', 3);
INSERT INTO `instalaciones` VALUES (26, 'Habitaciones 7', 'habitaciones-6.jpg', 'a', 3);
INSERT INTO `instalaciones` VALUES (27, 'Laboratorio', 'laboratorio-1.jpg', 'a', 8);
INSERT INTO `instalaciones` VALUES (28, 'Laboratorio 2', 'laboratorio-2.jpg', 'a', 8);
INSERT INTO `instalaciones` VALUES (29, 'Laboratorio 3', 'laboratorio-3.jpg', 'a', 8);
INSERT INTO `instalaciones` VALUES (30, 'Pediatría', 'pediatria-1.jpg', 'a', 9);
INSERT INTO `instalaciones` VALUES (31, 'Pediatría 2', 'pediatria-2.jpg', 'a', 9);
INSERT INTO `instalaciones` VALUES (32, 'Pediatría 3', 'pediatria-3.jpg', 'a', 9);
INSERT INTO `instalaciones` VALUES (33, 'Sala de espera', 'sala-de-espera-0_1.jpg', 'a', 1);
INSERT INTO `instalaciones` VALUES (34, 'Sala de espera 2', 'sala-de-espera-0_2.jpg', 'a', 1);
INSERT INTO `instalaciones` VALUES (35, 'Sala de espera 3', 'sala-de-espera-0.jpg', 'a', 1);
INSERT INTO `instalaciones` VALUES (36, 'Sala de espera 4', 'sala-de-espera-1.jpg', 'a', 1);
INSERT INTO `instalaciones` VALUES (37, 'Sala de espera 5', 'sala-de-espera-2.jpg', 'a', 1);
INSERT INTO `instalaciones` VALUES (38, 'Sala de espera 6', 'sala-de-espera-3.jpg', 'a', 1);
INSERT INTO `instalaciones` VALUES (39, 'Sala de espera 7', 'sala-de-espera-4.jpg', 'a', 1);
INSERT INTO `instalaciones` VALUES (40, 'Sala de espera 8', 'sala-de-espera-5.jpg', 'a', 1);
