INSERT INTO coberturas(nombre, imagen)
VALUES ("Valmed", "valmed.png"),
("Suterh Osperyh", "suterh-osperyh.png"),
("Osrja", "osrja.png"),
("Ospiv", "ospiv.png"),
("Ioma", "ioma.png"),
("Cover Salud", "cover-salud.png"),
("Bristol Medicine", "bristol-medicine.png"),
("Asmepriv", "asmepriv.png"),
("Scientis Medical", "scientis-medical.jpg"),
("Ospjn", "ospjn.jpg"),
("Ospia", "ospia.jpg"),
("Ospeca", "ospeca.jpg"),
("Ospa", "ospa.jpg"),
("Osecac", "osecac.jpg"),
("Galeno", "galeno.jpg"),
("Ensalud", "ensalud.jpg"),
("Comisarios Navales", "comisarios-navales.jpg"),
("Circulo Medico Matanza", "circulo-medico-matanza.jpg"),
("Activa Salud", "activa-salud.jpg"),
("Osmecon", "osmecon.gif");
