INSERT INTO servicios (nombre, descripcion, jefe) VALUES
("Laboratorio", "Análisis Clínicos y bacteriología con guardias permanentes las 24hs.", ""),
("Servicio de Radiología", "Estudios simples y contrastados con guardias permanentes las 24 hs.", ""),
("Servicio de Hemoterapia", "Con guardias permanentes las 24hs.", ""),
("Servicio Ambulatorio", "Electrocardiogramas, Ergometrías, Ecodoppler, Holter. Estudios Funcionales Respiratorios. Ecografías. Electromiograma, Potenciales Evocados. Audiometría y Otoemisiones Acústicas. Kinesiología. Fonoaudiología y Foniatría. Endoscopías: Fibroendoscopías Altas, Fibrocolonoscopía y Rectosigmoideoscopías. Test de Alergias. Ecocardiograma. Endoscopía. Fibrobroncoscopia.", ""),
("Servicio de Tomografía Computada", "Contando con 1 equipo helicoidal de última generación.", ""),
("Servicio de Hemodiálisis", "", ""),

("Servicio de Guardia", "La Guardia Externa cuenta con 5 amplios consultorios y funciona las 24hs los 365 días del año. Cuenta además con 6 puestos de Observación, 4 camas de hospital de día y Shock-room.", "Dra. Jannet Chacon"),
("Servicio de Internación", "El servicio cuenta con 140 camas. Todas las camas están ubicadas en habitaciones con baño privado, aire acondiconado frío / calor de regulación individual, TV por cable en pantallas de LCD.", "Dra. Marisa Flores"),
("Terapia Intensiva Polivalente", "El Sanatorio cuenta con 26 camas destinadas a la Alta  Complejidad Médica, esto es, Terapia Intensiva de Adultos, Unidad De Cuidados Especiales, Recuperación de Cirugía Cardiovascular.", "Dr. Nicolas D`Agostino"),
("Unidad de Cuidados Especiales", "", ""),
("Centro Quirúgico", "Contamos con cinco quirófanos de moderna tecnología en donde se realizan todo tipo de intervenciones quirúrgicas tanto ambulatorias como las que requieren internación.", ""),
("Servicio de Hemodinamia", "Cuenta con 1 salas de Hemodinamia de última generación con angiógrafo de alta resolución con detectores planos (Flat Detector) que permiten adquirir imágenes en forma digital de las arterias del corazón, sistema nervioso central y de la vasculatura periférica facilitando la realización de estudios diagnósticos y terapéuticos con imágenes de alta calidad. El área cuenta con sala de recuperación.", "Dr. Alejandro Garcia Escudero"),
("Servicio de Cirugía Cardiovascular", "Contamos con una sala de recuperación perioperatoria especializada, con personal médico y paramédico altamente entrenado y un soporte multidiciplinario (Enfermería, Kinesiología, Nefrología, Infectología, Neumonología, etc) que nos permite ofrecerle una atención jerarquizada de acuerdo a las características individuales de cada paciente.", "Dr. Luis Frank"),
("Servicio de Neurorehabilitación", "En nuestro centro de Neurorehabilitación ofrecemos y utilizamos diferentes métodos y tratamientos dependiendo del tipo de paciente. En el caso de las lesiones neurológicas el paciente pasa por una fase aguda en la cual necesita de unas atenciones médicas, a menudo hospitalarias, para estabilizarse clínicamente. Una vez superada esta fase, que pude durar desde unos meses hasta más de un año, el paciente puede retornar a su domicilio y es en ése momento donde puede asistir al centro a fin de recibir rehabilitación de forma ambulatoria. Después la valoración inicial, que es realizada por todos los servicios, se planifica un plan de rehabilitación integral en nuestro centro. Mayoritariamente atendemos pacientes que han sufrido las siguientes afectaciones neurológicas: Traumatismo cráneo-encefálico, Lesiones medulares (traumáticas, tumorales, víricas…), Ictus (accidentes vasculares cerebrales), Patología tumoral cerebral, Encefalitis, Lesiones de plexos y de nervios periféricos, Parálisis cerebral, Enfermedades Neurodegenerativas.", "Dr. Maximo Zimerman"),
("Servicio de Diagnóstico por Imagen", "Cuenta con un sistema de Integración digital de todos sus equipos lo que permite, de forma ágil y sencilla, que los estudios realizados estén disponibles rápidamente en las diferentes áreas del sanatorio para que los médicos solicitantes puedan visualizarlos en forma inmediata a su realización.", ""),
("Laboratorio", "El laboratorio de análisis clínico se encuentra absolutamente robotizado e informatizado y son el resultado de la búsqueda constante de nuevas metodologías más sensibles, específicas y eficientes para procesar mayor volumen de muestras en el menor tiempo posible.", "Dra. Amelia Galli");
