USE clinicaloscedros;

INSERT INTO empleado (id, nombre, imagen, titulo, cv, sexo) VALUES
(0, "Indefinido", "Indefinido", "Indefinido", "Indefinido", 'I'),
(1, "Germán Torres Molina", "", "Dr.",  "", 'M'),
(2, "Daniel Lambiase", "", "Dr.",  "", 'M'),
(3, "Edgardo Bonura", "", "Dr.",  "", 'M'),
(4, "Maibi Vela Jara", "", "Dra.",  "", 'F'),
(5, "Javier De Sensi", "", "Dr.",  "", 'M'),
(6, "Sandra Isasmendi", "", "Dra.",  "", 'F'),
(7, "Maite Miguelez", "", "Dra.",  "", 'F'),
(8, "Enrique Turina", "", "Dr.",  "", 'M'),
(9, "Marcelo Ghione", "", "Dr.",  "", 'M'),
(10, "Andres Rebaudi", "", "Dr.",  "", 'M'),
(11, "Pablo Teran", "", "Dr.",  "", 'M'),
(12, "Oswaldo Hennings", "", "Dr.",  "", 'M'),
(13, "Lidia Tricio", "", "Dra.",  "", 'F'),
(14, "Viviana Valencia", "", "Dra.",  "", 'F'),
(15, "Mariano Ganduglia", "", "Dr.",  "", 'M'),
(16, "Fabricio Ochoa", "", "Dr.",  "", 'M'),
(17, "Horacio Pampin", "", "Dr.",  "", 'M'),
(18, "Miguel Germano", "", "Dr.",  "", 'M'),
(19, "Carlos Meza", "", "Dr.",  "", 'M'),
(20, "Dominguez", "", "Dr.", "",  ''),
(21, "Freddy Pacheco", "", "Dr.",  "", 'M'),
(22, "Hugo D. Tedesco", "", "Dr.",  "", 'M'),
(23, "Jorge Poliak", "", "Dr.",  "", 'M'),
(24, "Liliana Zabala", "", "Dra.",  "", 'F'),
(25, "Natalia Romero", "", "Dra.",  "", 'F'),
(26, "Tomas Mendez", "", "Dr.",  "", 'M'),
(27, "Mariana Pampin", "", "Dra.",  "", 'F'),
(28, "Luis Paredes Chavez", "", "Dr.",  "", 'M'),
(29, "Cristian Cardenas", "", "Dr.",  "", 'M'),
(30, "Carolina Vilches", "", "Dra.",  "", 'F'),
(31, "Andrea Cid", "", "Dra.",  "", 'F'),
(32, "Gustavo Debaise", "", "Dr.",  "", 'M'),
(33, "Marta Garcia", "", "Dra.",  "", 'F'),
(34, "Claudia Efthymiadis", "", "Dra.",  "", 'F'),
(35, "Sonia Hermida", "", "Dra.",  "", 'F'),
(36, "José Ernesto Cafaro", "", "Dr.",  "", 'M'),
(37, "Mario Gorno", "", "Dr.",  "", 'M'),
(38, "Vicente Ranieli", "", "Dr.",  "", 'M'),
(39, "Gustavo Galparsoro", "", "Dr.",  "", 'M'),
(40, "Mabel Leidy Tejerina", "", "Dra.",  "", 'F'),
(41, "Carrizo", "", "Dr.", "",  ''),
(42, "Andres Ciccarello", "", "Dr.",  "", 'M'),
(43, "Bernardo Kaltman", "", "Dr.",  "", 'M'),
(44, "Anzaldo Rocha", "", "Dr.",  "", 'M'),
(45, "Gustavo Miranda", "", "Dr.",  "", 'M'),
(46, "Zenon Chumacero Sierra", "", "Dr.",  "", 'M'),
(47, "German Chico", "", "Dr.",  "", 'M'),
(48, "Cristian Sayago Gonzalez", "", "Dr.",  "", 'M'),
(49, "Gonzalo Crespi", "", "Dr.",  "", 'M'),
(50, "Guillermo Benchetrit", "", "Dr.",  "", 'M'),
(51, "Alberto Rodriguez Cetran", "", "Dr.",  "", 'M'),
(52, "Fabiana Fabre", "", "Dra.",  "", 'F'),
(53, "Mariela Penalva", "", "Dra.",  "", 'F'),
(54, "Pablo Aguilera", "", "Dr.",  "", 'M'),
(55, "Victorio Butera", "", "Dr.",  "", 'M'),
(56, "Roberto Talavera", "", "Dr.",  "", 'M'),
(57, "Andrea Zurzolo", "", "Dra.",  "", 'F'),
(58, "Marcos Auche", "", "Dr.",  "", 'M'),
(59, "Walter Otero", "", "Dr.",  "", 'M'),
(60, "Laura Sarasino", "", "Dra.",  "", 'F'),
(61, "Marina Blanco", "", "Dra.",  "", 'F'),
(62, "Mariano Costa", "", "Dr.", "",  ''),
(63, "Luis Guillermo Frank", "", "Dr.",  "", 'M'),
(64, "Luis Molteni", "", "Dr.",  "", 'M'),
(65, "Vanina Poggio", "", "Dra.",  "", 'F'),
(66, "Olga Zodziejko", "", "Dra.",  "", 'F'),
(67, "Mirta Salomon", "", "Dra.",  "", 'F'),
(68, "Felipe Gonzalez La Riva", "", "Dr.",  "", 'M'),
(69, "Carolina Guerra", "", "Dra.",  "", 'F'),
(70, "Gaston Occhionero", "", "Dr.",  "", 'M'),
(71, "Pablo Franconeri", "", "Dr.",  "", 'M'),
(72, "Graciela Ramos", "", "Dra.",  "", 'F'),
(73, "Guadalupe Rocha", "", "Dra.",  "", 'F'),
(74, "Luciana Gibilisco", "", "Dra.",  "", 'F'),
(75, "Di Spagna", "", "Dr.", "",  ''),
(76, "Jorge Borkowski", "", "Dr.",  "", 'M'),
(77, "Federico Dimase", "", "Dr.",  "", 'M'),
(78, "Hernan Piza", "", "Dr.",  "", 'M'),
(79, "Maria Cecilia Ardaris", "", "Dra.",  "", 'F'),
(80, "Silvana Bocca", "", "Dra.",  "", 'F'),
(81, "Johanna Furlan", "", "Dra.",  "", 'F'),
(82, "Florencia Paris", "", "Dra.",  "", 'F'),
(83, "Victoria Mamani", "", "Dra.",  "", 'F'),
(84, "Roxana Roatta", "", "Dra.",  "", 'F'),
(85, "Matias Berger", "", "Dr.",  "", 'M'),
(86, "Rodríguez Cetran", "", "Dr.",  "", 'M'),
(87, "Alejandro Hafez", "", "Sr.",  "", 'M'),
(88, "Vilma Di Pascua", "", "Lic.",  "", 'F'),
(89, "Marisa Flores", "", "Dra.",  "", 'F'),
(90, "Nicolas D’Agostino", "", "Dr.",  "", 'M'),
(91, "Jannet Chacon", "", "Dra.",  "", 'F'),
(92, "Alejandro García Escudero", "", "Dr.",  "", 'M'),
(93, "Alberto Marani", "", "Dr.",  "", 'M'),
(94, "Maximo Zimerman", "", "Dr.",  "", 'M'),
(95, "Juan D. Bonello", "", "Dr.",  "", 'M'),
(96, "Jorge Borkowsky", "", "Dr.",  "", 'M'),
(97, "Amelia Galli", "", "Dra.",  "", 'F'),
(98, "Mario A. Yarrouge", "", "Dr.", "", 'M'),
(99, "Caludia Zuñiga Teppa", "", "Dra.", "", "F"),
(100, "Juan Iturriaga Meza", "", "Dr.", "", "M"),
(101, "Daniel Eloff", "", "Dr.", "", "M"),
(102, "Zenon Chumacera Sierra", "", "Dr.", "", "M"),
(103, "Water Otero", "", "Dr.", "", "M"),
(104, "Richard Junco Colina", "", "Dr.", "", "M"),
(105, "Silvio J. Stupnik", "", "Dr.", "", "M"),
(106, "Carlos Alberto Costa", "", "Dr.", "", "M"),
(107, "Hernán Piza", "", "Dr.", "", "M"),
(108, "German Diaz", "", "Lic.", "", "M");
