USE clinicaloscedros;

INSERT INTO empleado (nombre, idCargo, sexo) VALUES
("Indefinido", 1, 'I'),
("Germán Torres Molina", 1, 'M'),
("Daniel Lambiase", 1, 'M'),
("Edgardo Bonura", 1, 'M'),
("Maibi Vela Jara", 2, 'F'),
("Javier De Sensi", 1, 'M'),
("Sandra Isasmendi", 2, 'F'),
("Maite Miguelez", 2, 'F'),
("Enrique Turina", 1, 'M'),
("Marcelo Ghione", 1, 'M'),
("Andrés Rebaudi", 1, 'M'),
("Pablo Teran", 1, 'M'),
("Osvaldo Hennings", 1, 'M'),
("Lidia Tricio", 2, 'F'),
("Viviana Valencia", 2, 'F'),
("Mariano Ganduglia", 1, 'M'),
("Fabricio Ochoa", 1, 'M'),
("Horacio Pampin", 1, 'M'),
("Miguel Germano", 1, 'M'),
("Carlos Meza", 1, 'M'),
("Dominguez", 1, 'M'),
("Freddy Pacheco", 1, 'M'),
("Hugo D. Tedesco", 1, 'M'),
("Jorge Poliak", 1, 'M'),
("Liliana Zabala", 2, 'F'),
("Natalia Romero", 2, 'F'),
("Tomás Mendez", 1, 'M'),
("Mariana Pampin", 2, 'F'),
("Luis Paredes Chavez", 1, 'M'),
("Cristian Cardenas", 1, 'M'),
("Carolina Vilches", 2, 'F'),
("Andrea Cid", 2, 'F'),
("Gustavo Debaise", 1, 'M'),
("Marta Garcia", 2, 'F'),
("Claudia Efthymiadis", 2, 'F'),
("Sonia Hermida", 2, 'F'),
("José Ernesto Cafaro", 1, 'M'),
("Mario Gorno", 1, 'M'),
("Vicente Ranieli", 1, 'M'),
("Gustavo Galparsoro", 1, 'M'),
("Mabel Leidy Tejerina", 2, 'F'),
("Carrizo", 1, 'M'),
("Andrés Ciccarello", 1, 'M'),
("Bernardo Kaltman", 1, 'M'),
("Anzaldo Rocha", 1, 'M'),
("Gustavo Miranda", 1, 'M'),
("Zenon Chumacero Sierra", 1, 'M'),
("Germán Chico", 1, 'M'),
("Cristian Sayago Gonzalez", 1, 'M'),
("Gonzalo Crespi", 1, 'M'),
("Guillermo Benchetrit", 1, 'M'),
("Alberto Rodriguez Cetran", 1, 'M'),
("Fabiana Fabre", 2, 'F'),
("Mariela Penalva", 2, 'F'),
("Pablo Aguilera", 1, 'M'),
("Victorio Butera", 1, 'M'),
("Roberto Talavera", 1, 'M'),
("Andrea Zurzolo", 2, 'F'),
("Marcos Auche", 1, 'M'),
("Walter Otero", 1, 'M'),
("Laura Sarasino", 2, 'F'),
("Marina Blanco", 2, 'F'),
("Mariano Costa", 1, ''),
("Luis Guillermo Frank", 1, 'M'),
("Luis Molteni", 1, 'M'),
("Vanina Poggio", 2, 'F'),
("Olga Zodziejko", 2, 'F'),
("Mirta Salomon", 2, 'F'),
("Felipe Gonzalez La Riva", 1, 'M'),
("Carolina Guerra", 2, 'F'),
("Gaston Occhionero", 1, 'M'),
("Pablo Franconeri", 1, 'M'),
("Graciela Ramos", 2, 'F'),
("Guadalupe Rocha", 2, 'F'),
("Luciana Gibilisco", 2, 'F'),
("Di Spagna", 1, 'M'),
("Jorge Borkowski", 1, 'M'),
("Federico Dimase", 1, 'M'),
("Hernán Piza", 1, 'M'),
("Maria Cecilia Ardaris", 2, 'F'),
("Silvana Bocca", 2, 'F'),
("Johanna Furlan", 2, 'F'),
("Florencia Paris", 2, 'F'),
("Victoria Mamani", 2, 'F'),
("Roxana Roatta", 2, 'F'),
("Matias Berger", 1, 'M'),
("Alejandro Hafez", 3, 'M'),
("Vilma Di Pascua", 8, 'F'),
("Marisa Flores", 2, 'F'),
("Nicolás D’Agostino", 1, 'M'),
("Jannet Chacon", 2, 'F'),
("Alejandro García Escudero", 1, 'M'),
("Alberto Marani", 1, 'M'),
("Maximo Zimerman", 1, 'M'),
("Juan D. Bonello", 1, 'M'),
("Jorge Borkowsky", 1, 'M'), /* Duplicado (por mala escritura) */
("Amelia Galli", 2, 'F'),
("Mario A. Yarrouge", 1, 'M'),
("Claudia Zuñiga Teppa", 2, "F"),
("Juan Iturriaga Meza", 1, "M"),
("Daniel Eloff", 1, "M"),
("Zenon Chumacera Sierra", 1, "M"),
("Walter Otero", 1, "M"),
("Richard Junco Colina", 1, "M"),
("Silvio J. Stupnik", 1, "M"),
("Carlos Alberto Costa", 1, "M"),
("Hernán Piza", 1, "M"),
("Germán Diaz", 7, "M");
