INSERT INTO especialidades (nombre)
VALUES ("Alergia y Neumología"),
("Anestesiología Cardiovascular"),
("Cirugía Cabeza y Cuello"),
("Cirugía General <b>(guardia permanente)</b>"),
("Cirugía Infantil"),
("Cirugía Plástica reparadora"),
("Cirugía Vascular"),
("Clínica Médica <b>(guardia permanente)</b>"),
("Columna"),
("Diabetes y Nutrición"),
("Dietología"),
("Dermatología"),
("Ecografías <b>(guardia permanente)</b>"),
("Endocrinología"),
("Especialista en Flebología"),
("Gastroenterología"),
("Ginecología y obstetricia <b>(guardia permanente)</b>"),
("Hematología"),
("Infectología"),
("Nefrología"),
("Neumonología"),
("Neurocirugía"),
("Neurología"),
("Obstetricia"),
("Oftalmología"),
("Otorrinolaringología"),
("Patología Mamaria"),
("Pediatría <b>(guardia permanente)</b>"),
("Reumatología"),
("Traumatología <b>(guardia permanente)</b>"),
("Urología");
