INSERT INTO especialidades (id, nombre) VALUES
(1, 'Alergia y Neumología'),
(2, 'Anestesiología Cardiovascular'),
(3, 'Cirugía Cabeza y Cuello'),
(4, 'Cirugía General <b>(guardia permanente)</b>'),
(5, 'Cirugía Infantil'),
(6, 'Cirugía Plástica Reparadora'),
(7, 'Cirugía Vascular'),
(8, 'Clínica Médica <b>(guardia permanente)</b>'),
(9, 'Columna'),
(10, 'Diabetes y Nutrición'),
(11, 'Dietología'),
(12, 'Dermatología'),
(13, 'Ecografías <b>(guardia permanente)</b>'),
(14, 'Endocrinología'),
(15, 'Especialista en Flebología'),
(16, 'Gastroenterología'),
(17, 'Ginecología y obstetricia <b>(guardia permanente)</b>'),
(18, 'Hematología'),
(19, 'Infectología'),
(20, 'Nefrología'),
(21, 'Neumonología'),
(22, 'Neurocirugía'),
(23, 'Neurología'),
(24, 'Obstetricia'),
(25, 'Oftalmología'),
(26, 'Otorrinolaringología'),
(27, 'Patología Mamaria'),
(28, 'Pediatría <b>(guardia permanente)</b>'),
(29, 'Reumatología'),
(30, 'Traumatología <b>(guardia permanente)</b>'),
(31, 'Urología'),
(32, 'Cardiología'),
(33, 'Fonoaudilogía'),
(34, 'Cirugía Torácica'),
(35, 'Cardiología Infantil'),
(36, 'Oncología'),
(37, 'Fibrobroncospía');
